export const SET_CHARACTERS = 'SET_CHARACTERS';
export const SET_COUNT = 'SET_COUNT';
export const HANDLE_CHARACTER = 'HANDLE_CHARACTER';
export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';

